import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {createOvernightWorker,inspectOvernightReceipt,inspectOvernightReceipts} from '../lib/overnight-worker.mjs';
const hash=x=>createHash('sha256').update(x).digest('hex');
function setup(t){const base=fs.mkdtempSync(path.join(os.tmpdir(),'worker-adapter-'));t.after(()=>fs.rmSync(base,{recursive:true,force:true}));const directory=path.join(base,'runs'),intentDirectory=path.join(base,'intents');fs.mkdirSync(directory);const manifestPath=path.join(base,'approved.json');const batch={schema:1,unresolved_decisions:[],tasks:[{id:'check',approved:true,cwd:base,argv:['true'],preflight:[['true']],verify:[['true']],timeout_seconds:5}]};fs.writeFileSync(manifestPath,JSON.stringify(batch));const authorization={scope:'fixture check only',revision:'v1',approvedTaskIds:['check'],manifestSha256:hash(fs.readFileSync(manifestPath))};const request={idempotencyKey:'one',authorization,manifestPath};const now=Date.now();return{base,directory,intentDirectory,manifestPath,authorization,request,now,make:opts=>createOvernightWorker({directory,intentDirectory,runner:'/fixture/runner.py',now:()=>now,...opts})};}
function receipt(s,manifest,id='123',changes={}){const root=path.join(s.directory,id);fs.mkdirSync(root);const b=fs.readFileSync(manifest);fs.writeFileSync(path.join(root,'batch.json'),b);fs.writeFileSync(path.join(root,'launch.json'),JSON.stringify({unit:`bamware-overnight-${id}`,smoke_test:true}));fs.writeFileSync(path.join(root,'pickup.json'),JSON.stringify({task_pid:42,task:'check',at:s.now/1000,batch_sha256:hash(b)}));fs.writeFileSync(path.join(root,'status.json'),JSON.stringify({phase:'finished',finished_at:s.now/1000,tasks:[{id:'check',state:'verified',exit_code:0,finished_at:s.now/1000}],...changes}));return root;}
test('disabled worker cannot execute even with authorized manifest',async t=>{const s=setup(t);let calls=0;const a=s.make({execute:async()=>{calls++}});assert.equal((await a.dispatch(s.request)).state,'disabled');assert.equal(calls,0);});
test('wrong manifest/scope is rejected before intent or launch',async t=>{const s=setup(t);let calls=0;const a=s.make({enabled:true,execute:async()=>{calls++}});await assert.rejects(()=>a.dispatch({...s.request,authorization:{...s.authorization,manifestSha256:'bad'}}),/hash mismatch/);await assert.rejects(()=>a.dispatch({...s.request,authorization:{...s.authorization,approvedTaskIds:['other']}}),/scope mismatch/);assert.equal(calls,0);});
test('actual adapter contract observes fixture receipt and never repeats launch after restart',async t=>{const s=setup(t);let calls=0;const execute=async(_bin,args)=>{calls++;const intents=fs.readdirSync(s.intentDirectory).filter(x=>x.endsWith('.json'));assert.equal(intents.length,1);receipt(s,args[2]);};const a=s.make({enabled:true,execute});const first=await a.dispatch(s.request);assert.equal(first.accepted,true);assert.equal(first.state,'verified_result_recorded');const restart=s.make({enabled:true,execute});assert.equal((await restart.dispatch(s.request)).id,first.id);assert.equal(calls,1);await assert.rejects(()=>restart.dispatch({...s.request,authorization:{...s.authorization,revision:'v2'}}),/changed authorization/);});
test('timeout persists unknown intent and lookup does not invoke worker',async t=>{const s=setup(t);let calls=0;const execute=async()=>{calls++;throw Error('timeout')};const a=s.make({enabled:true,execute});assert.equal((await a.dispatch(s.request)).accepted,false);await s.make({enabled:true,execute}).dispatch(s.request);assert.equal(calls,1);});
test('same manifest in a separate invocation cannot borrow old receipt',async t=>{const s=setup(t);const a=s.make({enabled:true,execute:async(_b,args)=>{receipt(s,args[2]);}});await a.dispatch(s.request);const b=s.make({enabled:true,execute:async()=>{throw Error()}});assert.equal((await b.dispatch({...s.request,idempotencyKey:'two'})).accepted,false);});
test('ambiguous receipts and tampered batch never count as pickup',async t=>{const s=setup(t);const a=s.make({enabled:true,execute:async(_b,args)=>{receipt(s,args[2],'123');receipt(s,args[2],'124');}});assert.equal((await a.dispatch(s.request)).state,'ambiguous_receipts');fs.writeFileSync(path.join(s.directory,'123','batch.json'),'{}');assert.equal(inspectOvernightReceipts(s.directory).find(x=>x.id==='123').state,'source_unavailable');});
test('probe binds task/manifest/revision/freshness; verify failure stays blocked',async t=>{const s=setup(t);const a=s.make({enabled:true,execute:async(_b,args)=>receipt(s,args[2])});const r=await a.dispatch(s.request);const expected={idempotencyKey:'one',taskId:'check',expectedManifestHash:r.manifestHash,expectedRevision:'v1'};assert.equal((await a.probe(expected)).state,'resolved');assert.equal((await a.probe({...expected,expectedRevision:'v2'})).state,'unavailable');assert.equal((await a.probe({...expected,taskId:'other'})).state,'unavailable');const late=s.make({now:()=>s.now+100000});assert.equal((await late.probe({...expected,maxAgeMs:50000})).state,'unavailable');const p=path.join(s.directory,'123','status.json');const status=JSON.parse(fs.readFileSync(p));status.tasks[0].state='failed';status.tasks[0].exit_code=1;fs.writeFileSync(p,JSON.stringify(status));assert.equal((await a.probe(expected)).state,'blocked');});
