#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# ──────────────────────────────────────────────────────────────────────────
# Bamware keys wizard — puts every key in ONE place (AWS SSM Parameter Store,
# /bamware/...) and pushes it to wherever it is consumed. Re-runnable: each
# stage skips itself when the vault already has the value. See docs/secrets.md.
# ──────────────────────────────────────────────────────────────────────────

PROFILE="${BAMWARE_AWS_PROFILE:-bamware}"
REGION="${BAMWARE_AWS_REGION:-us-east-1}"
AWS="aws --profile $PROFILE --region $REGION"
VENUE_DIR="${VENUE_ENGINE_DIR:-$HOME/code/bamware-venue-engine}"
AUTH_URL="${AUTH_URL:-https://cje3ppxv47.execute-api.us-east-1.amazonaws.com}"
VENUE_URL="${VENUE_URL:-https://venuekit-ashen.vercel.app}"
DEV_SECRET_ID="bamware/dev/app"   # Secrets Manager JSON the auth Lambda loads at cold start

vault_has() { $AWS ssm get-parameter --name "$1" --with-decryption --query Parameter.Value --output text >/dev/null 2>&1; }
vault_get() { $AWS ssm get-parameter --name "$1" --with-decryption --query Parameter.Value --output text; }
vault_put() { $AWS ssm put-parameter --name "$1" --value "$2" --type SecureString --overwrite >/dev/null && printf '  %s✓%s vault %s\n' "$GREEN" "$RESET" "$1"; }
# secret_merge KEY VALUE — merge one key into the auth Lambda's Secrets Manager JSON (never echoes values)
secret_merge() {
  local current merged
  current=$($AWS secretsmanager get-secret-value --secret-id "$DEV_SECRET_ID" --query SecretString --output text)
  merged=$(K="$1" V="$2" python3 -c 'import json,os,sys; d=json.loads(sys.stdin.read()); d[os.environ["K"]]=os.environ["V"]; print(json.dumps(d))' <<<"$current")
  $AWS secretsmanager put-secret-value --secret-id "$DEV_SECRET_ID" --secret-string "$merged" >/dev/null
  printf '  %s✓%s Secrets Manager %s.%s updated\n' "$GREEN" "$RESET" "$DEV_SECRET_ID" "$1"
}
# vercel_env NAME VALUE — set a production env var on the venue-engine project (replaces if present)
vercel_env() {
  ( cd "$VENUE_DIR" && npx --yes vercel env rm "$1" production --yes >/dev/null 2>&1 || true
    printf '%s' "$2" | npx --yes vercel env add "$1" production >/dev/null ) && printf '  %s✓%s Vercel venuekit production %s\n' "$GREEN" "$RESET" "$1"
}

banner "Bamware keys — Google, Apple, push, and the two server secrets"

stage "Preflight: AWS vault + Vercel access"
  step "Checking the AWS profile '$PROFILE' (region $REGION) can reach the vault…"
  if ! $AWS sts get-caller-identity --query Account --output text >/dev/null 2>&1; then
    warn "AWS profile '$PROFILE' is not usable. Run: aws configure --profile $PROFILE  (the deployer key from 1Password/your notes), then re-run."
    exit 1
  fi
  say "AWS ok. Vault entries today:"
  $AWS ssm describe-parameters --parameter-filters "Key=Name,Option=BeginsWith,Values=/bamware" --query 'Parameters[].Name' --output text | tr '\t' '\n' | sed 's/^/    /'
  step "Checking Vercel login (for the venue engine's env vars)…"
  if ! npx --yes vercel whoami >/dev/null 2>&1; then warn "Not logged in to Vercel. Run: npx vercel login   then re-run."; exit 1; fi
  [[ -f "$VENUE_DIR/.vercel/project.json" ]] || { warn "$VENUE_DIR is not linked to the venuekit Vercel project (run 'npx vercel link' there)."; exit 1; }
  say "Vercel ok."
  pause

stage "Google sign-in: two OAuth client ids"
  if vault_has /bamware/brewdesk/google-ios-client-id && vault_has /bamware/brewdesk/google-server-client-id; then
    say "Already in the vault — skipping."
  else
    say "Google needs one client id for the iPhone app and one for our server."
    open_url "https://console.cloud.google.com/apis/credentials"
    step "Pick (or create) the project you want BrewDesk under, then: Create credentials → OAuth client ID."
    step "If asked to configure the consent screen first: External, app name 'BrewDesk', your email, save."
    step "Client 1 — Application type: iOS. Name: 'BrewDesk iOS'. Bundle ID: io.bamware.brewdesk. Create. Copy the Client ID (ends in .apps.googleusercontent.com)."
    ask GOOGLE_IOS_CLIENT_ID "Paste the iOS client id"
    step "Client 2 — Create credentials → OAuth client ID → Application type: Web application. Name: 'Bamware auth server'. No URIs needed. Create. Copy the Client ID."
    ask GOOGLE_SERVER_CLIENT_ID "Paste the Web/server client id"
    vault_put /bamware/brewdesk/google-ios-client-id "$GOOGLE_IOS_CLIENT_ID"
    vault_put /bamware/brewdesk/google-server-client-id "$GOOGLE_SERVER_CLIENT_ID"
  fi
  IOS_ID=$(vault_get /bamware/brewdesk/google-ios-client-id); SRV_ID=$(vault_get /bamware/brewdesk/google-server-client-id)
  step "Telling the auth service to accept these ids (Secrets Manager → GOOGLE_CLIENT_IDS)…"
  confirm "Update the auth Lambda's secret now? (safe: only adds/replaces GOOGLE_CLIENT_IDS)" && secret_merge GOOGLE_CLIENT_IDS "$IOS_ID,$SRV_ID"
  say "The app-side Info.plist entry (GIDClientID + URL scheme) is a code change: an agent will open that PR from the vault value."
  pause

stage "Apple: turn on Sign in with Apple for the app id"
  say "This is a checkbox in Apple's portal. No value to copy."
  open_url "https://developer.apple.com/account/resources/identifiers/list"
  step "Click the App ID 'io.bamware.brewdesk' (BrewDesk)."
  step "Under Capabilities tick 'Sign In with Apple' (leave 'Enable as a primary App ID'), then Save → Confirm."
  step "Xcode may ask to regenerate the provisioning profile the next time it builds; say yes."
  confirm "Done?" || warn "Skipped — the Apple button will fail at runtime until this is on."
  pause

stage "Apple: push notifications key (APNs)"
  if vault_has /bamware/shared/apns-key-p8-b64 && vault_has /bamware/shared/apns-key-id; then
    say "Already in the vault — skipping."
  else
    say "One key works for every Bamware app. Apple lets you download the file ONCE, so save it somewhere before continuing."
    open_url "https://developer.apple.com/account/resources/authkeys/list"
    step "Click '+'. Key Name: 'Bamware APNs'. Tick 'Apple Push Notifications service (APNs)'. Continue → Register."
    step "Click Download (AuthKey_XXXXXXXXXX.p8). Note the Key ID shown on that page."
    ask APNS_KEY_FILE "Path to the downloaded .p8 file (drag it into the terminal)"
    ask APNS_KEY_ID "Key ID (10 characters)"
    ask APPLE_TEAM_ID "Team ID (top-right of the portal, 10 characters)"
    vault_put /bamware/shared/apns-key-p8-b64 "$(base64 < "${APNS_KEY_FILE/#\~/$HOME}" | tr -d '\n')"
    vault_put /bamware/shared/apns-key-id "$APNS_KEY_ID"
    vault_put /bamware/shared/apple-team-id "$APPLE_TEAM_ID"
    say "You can delete the local .p8 now; the vault is the copy of record."
  fi
  say "Terraform reads these when you apply the push-service PR (bamware-infra #10)."
  pause

stage "Venue engine: JWT secret (so saved-spots sync trusts logins)"
  say "The auth service already has this secret; the venue engine just needs the same value. Nothing to copy by hand."
  if confirm "Copy JWT_SECRET from the auth Lambda's secret into the venue engine (Vercel, production) and the vault?"; then
    JWT=$($AWS secretsmanager get-secret-value --secret-id "$DEV_SECRET_ID" --query SecretString --output text | python3 -c 'import sys,json; print(json.loads(sys.stdin.read())["JWT_SECRET"])')
    vault_put /bamware/auth/dev/jwt-secret "$JWT"
    vercel_env JWT_SECRET "$JWT"
    unset JWT
  fi
  pause

stage "Venue engine: admin key (moderation screen)"
  if vault_has /bamware/venue-engine/admin-key; then say "Already in the vault — reusing."; ADMIN=$(vault_get /bamware/venue-engine/admin-key)
  else ADMIN=$(openssl rand -hex 32); vault_put /bamware/venue-engine/admin-key "$ADMIN"; say "Generated a random key (never shown)."; fi
  vercel_env ADMIN_KEY "$ADMIN"; unset ADMIN
  pause

stage "Redeploy the venue engine and verify"
  step "Vercel env changes need a redeploy. Redeploying the current production deployment…"
  ( cd "$VENUE_DIR" && LATEST=$(npx --yes vercel ls --prod 2>/dev/null | grep -oE 'https://[a-z0-9.-]+\.vercel\.app' | head -1); [[ -n "$LATEST" ]] && npx --yes vercel redeploy "$LATEST" >/dev/null 2>&1 ) && say "Redeploy requested." || warn "Could not redeploy automatically — the next merge to main will pick the env up."
  say "Waiting 60 s for the deploy…"; sleep 60
  code=$(curl -s -o /dev/null -w '%{http_code}' "$VENUE_URL/v1/users/me/saved")
  if [[ "$code" == "401" ]]; then say "✓ venue engine now checks logins (401 without a token)."; else warn "venue engine answered $code (503 = secret not live yet; re-run this stage after the deploy finishes)."; fi
  prov=$(curl -s "$AUTH_URL/auth/tenants/bamware-brewdesk/providers")
  say "auth service providers: $prov"
  say "Google sign-in becomes live once the app ships GIDClientID (agent PR) — the server side is ready."
  pause

finish
